minify: '{{ENV.NODE_ENV === "production"}}'
styleguide:
  css: []
hash:
  enabled: false
scripts:
  files:
    'single.js': '{{ assetPath }}/single.js'
    'multi.js': '{{ assetPath }}/multi.js'
stylesheets:
  files:
    'common.css': '{{ assetPath }}/common.css'
tasks:
  default:
    -
      - 'clean'
    -
      - 'stylesheets'
      - 'scripts'
      - 'svgsprite'
  dev:
    - 'default'
    - 'watcher'
  prod:
    - 'default'
    - 'hash'
