debug: true
s3:
  bucket: '{{ENV.AWS_BUCKET}}'
  accessKey: '{{ENV.AWS_ACCESS_KEY_ID}}'
  secretAccessKey: '{{ENV.AWS_SECRET_ACCESS_KEY}}'
  region: '{{ENV.AWS_DEFAULT_REGION}}'
  profile: '{{ENV.AWS_PROFILE}}'
minimumImageSize:
  width: '{{ENV.MIN_WIDTH}}'
  height: '{{ENV.MIN_HEIGHT}}'
s3Host: "{{ENV.S3_HOST}}"
quality: '{{ENV.QUALITY || 80}}'
folder: '{{ENV.FOLDER}}'
public: '{{(ENV.PUBLIC == "1")}}'
allowedExtensions: '{{ ENV.ALLOWED_EXTENSIONS || ".jpg,.jpeg,.png,.svg"}}'
maxAge: 31536000
plugins:
  hapi-logr:
    exclude:
      - 'client'
  vision:
  inert:
  hapi-upload-s3:
    _dependencies:
      - 'vision'
      - 'inert'
    bucket: '{{s3.bucket}}'
    accessKey: '{{s3.accessKey}}'
    secretAccessKey: '{{s3.secretAccessKey}}'
    region: '{{s3.region}}'
    profile: 'default'
    maxUploadSize: 30
  hapi-favicon:
  hapi-robots:
    envs:
      production:
        '*': ['/']
