name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{steps.branch.outputs.branch}}
    steps:
      # Set up branch name (Used for staging urls and image tags)
      -
        name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      -
        name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
      -
        name: Save Branch name
        id: branch
        run: echo "branch=${{env.BRANCH_NAME}}" >> $GITHUB_OUTPUT
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # Build images
      -
        name: Build and push API
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: firstandthird/micro-media:${{needs.setup.outputs.branch}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
